# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dloginApp', '0003_auto_20160719_0151'),
        ('coursesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_id',
        ),
        migrations.AddField(
            model_name='courses',
            name='user_id',
            field=models.ManyToManyField(to='dloginApp.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dloginApp.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
